### ISSUE TITLE
Spike: Pesquisar possibilidade de utilizar MariaDB

### ISSUE THREAD

**Issue by vcwild** [aHub-Tech/Live-Divulgador#9]
Poderia ser aberta uma issue para analizar a viabilidade de trocar o postgres pelo mariadb para que não possuam mais dependencias como a "libpq-dev"

_Originally posted by @chrisemke in https://github.com/aHub-Tech/Live-Divulgador/pull/6#pullrequestreview-776713178_

**Comment by chrisemke** [comment]
There is an official doc of them with sqlalchemy and docker, I think that if it decides to be applied, we will eliminate the need for these annoying dependencies, because of what I've been studying.
[mariadb+sqlalchemy+docker](https://mariadb.com/resources/blog/using-sqlalchemy-with-mariadb-connector-python-part-1/)

**Comment by RodrigoDornelles** [comment]
> Poderia ser aberta uma issue para analizar a viabilidade de trocar o postgres pelo mariadb para que não possuam mais dependencias como a "libpq-dev"
> 
> _Originally posted by @chrisemke in [#6 (review)](https://github.com/aHub-Tech/Live-Divulgador/pull/6#pullrequestreview-776713178)_

qual seria o problema em questão com a dependência sob "libpq-dev" ?
